### ISSUE TITLE
Repetitive crash of the editor for when randomly clicking on entities on scene

### ISSUE THREAD

**Issue by omomthings** [kotcrab/VisEditor#104]
Working on a brand new scene the editor crashes randomly for no appearing reason, I juste click on another element on scene to un-select the selected one and sometimes the editor crashes, with that i lost all what I didnt save, made me think of an auto save backup maybe good while the editor is not stable enough.. here is a bunch of crash log for the same reason, the same manipulation.
[viseditor-crash 15-12-22 17-09-17.txt](https://github.com/kotcrab/VisEditor/files/70028/viseditor-crash.15-12-22.17-09-17.txt)
[viseditor-crash 15-12-22 17-38-44.txt](https://github.com/kotcrab/VisEditor/files/70029/viseditor-crash.15-12-22.17-38-44.txt)
[viseditor-crash 15-12-22 17-43-20.txt](https://github.com/kotcrab/VisEditor/files/70030/viseditor-crash.15-12-22.17-43-20.txt)
[viseditor-crash 15-12-22 17-52-20.txt](https://github.com/kotcrab/VisEditor/files/70031/viseditor-crash.15-12-22.17-52-20.txt)

**Comment by kotcrab** [comment]
I have found and fixed two issues, crashes when using RotateTool and exporting scene which used string group ids. I'm not sure about this:
```
java.lang.IllegalStateException: EntitiesCollector didn't find any matching entity
	at com.kotcrab.vis.editor.module.scene.system.EntitiesCollector.createSelectionFragment(EntitiesCollector.java:70)
	at com.kotcrab.vis.editor.module.scene.entitymanipulator.EntitiesSelection.append(EntitiesSelection.java:99)
	at com.kotcrab.vis.editor.module.scene.entitymanipulator.EntityManipulatorModule.selectAppend(EntityManipulatorModule.java:619)
```
May be fixed but I need to test more, If it happens again, please post more logs. It is definitely related to groups.

>with that i lost all what I didnt save, made me think of an auto save backup maybe good while the editor is not stable enough

See #105

**Comment by omomthings** [comment]
groups? i wonder how it can be related to groups since I didn't have any entity group in my scene! I have different layers but I definitely don't have any group.. when you release a build with those fix's i'll try again and keep you informed!

**Comment by kotcrab** [comment]
Ow, actually, it may be related to layers. [Snapshot](http://dl.kotcrab.com/vis/editor/edge/VisEditor-edge-20151222-4.zip) build is already available.

**Comment by omomthings** [comment]
I have tested the new release, I think that the problem is solved, may need to wait more and test more to be sure... your call

**Comment by kotcrab** [comment]
`EntitiesCollector didn't find any matching entity` still occurs, I'm searching for reliable way to reproduce it.

**Comment by omomthings** [comment]
tried various ways, can't reproduce it, earlier it was caused when i was directly working on the properties of an entity and then selected a different one (from the same layer) but cant reproduce it

**Comment by kotcrab** [comment]
Alright, I hope it fixed all those issues so I'm closing this. Please reopen or create new issue if this still occurs.

**Comment by omomthings** [comment]
ok of course ! :)

**Comment by omomthings** [comment]
@kotcrab you changed something in the output scene, now the scene files don't work anymore on runtime, in the scene file here is the difference with a previous working version of the same file
actual file:   groupIds:{}
working version:  groupsIds:{size:0,entries:[]}
I dont think that it would need to be declared as a new issue since it is a result of a minor modification..

**Comment by kotcrab** [comment]
Yes, it was necessary to fix one of the issues. You will need to reexport your scenes and use runtime 0.3.1-SNAPSHOT.
