### ISSUE TITLE
MenuItem: visual glitch

### ISSUE THREAD

**Issue by code-disaster** [kotcrab/VisEditor#42]
Seems to happen only with a certain label text length, and (or?) with a shortcut set. The menu item background leaks left and right of the outlined area.

<img width="261" alt="screen shot 2015-10-02 at 14 18 38" src="https://cloud.githubusercontent.com/assets/4644167/10246376/f7b696dc-6910-11e5-8e58-fe5d599dc949.png">

**Comment by kotcrab** [comment]
Could you create SSCCE? Looks like creating MenuItem with that text and shortcut is not enough to reproduce or it was somehow already fixed in latest VisUI.

**Comment by code-disaster** [comment]
Very odd. Still happening here even with the simplified application.

This is built with VisUI 0.9.0-SNAPSHOT and libGDX 1.6.5.

```java
package com.codedisaster.demo;

import com.badlogic.gdx.*;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.utils.viewport.ScreenViewport;
import com.kotcrab.vis.ui.VisUI;
import com.kotcrab.vis.ui.widget.*;

public class MenuItemDemo extends ApplicationAdapter {

	OrthographicCamera screenCamera;

	Stage ui;
	InputMultiplexer input;

	@Override
	public void create () {
		VisUI.load();
	}

	@Override
	public void dispose() {
		ui.dispose();
		VisUI.dispose();
	}

	@Override
	public void resize(int width, int height) {
		if (ui != null) {
			ui.dispose();
		}

		screenCamera = new OrthographicCamera(width, height);

		ui = new Stage(new ScreenViewport(screenCamera));
		setupUI();

		input = new InputMultiplexer();
		input.addProcessor(ui);
		Gdx.input.setInputProcessor(input);
	}

	@Override
	public void render () {
		ui.act(Gdx.graphics.getRawDeltaTime());
		ui.draw();
	}

	private void setupUI() {
		Table root = new Table();

		MenuBar menuBar = new MenuBar();
		root.add(menuBar.getTable()).top().fillX().expandX().row();

		Menu viewMenu = new Menu("View");
		menuBar.addMenu(viewMenu);

		MenuItem showDebugGridItem = new MenuItem("Toggle tile grid");
		viewMenu.addItem(showDebugGridItem);
		showDebugGridItem.setShortcut(Input.Keys.SYM, Input.Keys.G);

		root.left().top().pad(8).setFillParent(true);
		ui.addActor(root);
	}

}
```

**Comment by code-disaster** [comment]
Ah! I found it! I need to call MenuItem.setShortcut() **before** Menu.addItem().

**Comment by kotcrab** [comment]
Guess it should call `invalidateHierarchy` after setting shortcut, I'll add that. `setShorcut` returns MenuItem so you can chain it with item creation.

Btw since 0.8.2 `setShorcut(int... keycodes)` is OS dependent, if you call it with `setShortcut(Input.Keys.CONTROL_LEFT, Input.Keys.G)`, it will be Ctrl+G on Win and Linux, and ⌘G on Mac.
